stackName: cumulus-api-lpdaac
stage: dev

distributionEndpoint: https://cumulus.developmentseed.org/distribution

buckets:
  private: cumulus-private
  public: cumulus-public
  protected: cumulus-protected
  internal: cumulus-internal

ecs:
  subnet: subnet-623b1639 # cumulus-api-private-subnet on vpc-50286536
  availabilityZone: us-east-1a
  securityGroup: sg-8503f5fa
  maxInstances: 5
  desiredInstances: 2
  keyPairName: cumulus-scisco
  instanceType: m4.large

# processing docker images
images:
  - name: asterProcessing
    image: cumulus-docker-dev-aster
    cpu: 25
    memory: 400

  - name: modisProcessing
    image: cumulus-docker-dev-modis
    cpu: 25
    memory: 400

elasticsearch:
  # the dynamic template that is included with every type
  # used with the bootstrap command
  dynamic_templates:
    - all_date_fileds:
        match_mapping_type: long
        match: '*At'
        mapping:
          type: date
  relations:
    - CollectionsTable
    - PDRsTable

sqs:
  - name: PDRsQueue # queue for list of PDRs to be parsed
    visibilityTimeout: 120
    retry: 3
  - name: GranulesQueue # queue for Granule files to be ingested
    visibilityTimeout: 300
    retry: 3
  - name: ProcessingQueue # queue for running process ECS tasks
    visibilityTimeout: 300
    retry: 2
  - name: DispatcherFailedQueue # queue for lambda messages that failed
    visibilityTimeout: 120

dynamos:
  - name: CollectionsTable
    read: 5
    write: 5
    envName: CollectionsTable
    elasticsearch: true
    attributes:
      - name: collectionName
        type: S
    schema:
      - name: collectionName
        type: HASH

  - name: ProvidersTable
    read: 5
    write: 5
    envName: ProvidersTable
    elasticsearch: true
    attributes:
      - name: name
        type: S
    schema:
      - name: name
        type: HASH

  - name: GranulesTable
    read: 300
    write: 300
    envName: GranulesTable
    elasticsearch: true
    attributes:
      - name: granuleId
        type: S
    schema:
      - name: granuleId
        type: HASH

  - name: PDRsTable
    read: 100
    write: 100
    envName: PDRsTable
    elasticsearch: true
    attributes:
      - name: pdrName
        type: S
    schema:
      - name: pdrName
        type: HASH

  - name: DistributionTable
    read: 1
    write: 20
    envName: DistributionTable
    elasticsearch: true
    attributes:
      - name: userName
        type: S
      - name: accessDate
        type: N
    schema:
      - name: userName
        type: HASH
      - name: accessDate
        type: RANGE

  - name: UsersTable
    read: 100
    write: 1
    envName: UsersTable
    attributes:
      - name: userName
        type: S
    schema:
      - name: userName
        type: HASH



# difining the APIs. Each item will include a separate endpoint
apis:
  - name: distribution
  - name: backend

lambdas:
  - name: es
    handler: es.handler
    timeout: 300

  - name: ingest
    handler: ingest.handler
    timeout: 300
    services:
      - name: parsePdrs
        count: 1 # number of service instances running on ECS for this lambda
        image: cumulus-docker-dev-lambdarunner
        memory: 256
        cpu: 5
        commands:
          - --eventJson
          - '{ \"action\": \"parse\" }'

      - name: ingestGranules
        image: cumulus-docker-dev-lambdarunner
        count: 1
        memory: 512
        cpu: 10
        commands:
          - --eventJson
          - '{ \"action\": \"download\" }'

      - name: discoverPdrs
        image: cumulus-docker-dev-lambdarunner
        count: 1
        memory: 256
        cpu: 5
        commands:
          - --eventJson
          - '{ \"action\": \"discover\" }'

  - name: runner
    handler: runner.handler
    timeout: 300
    services:
      - name: runner
        image: cumulus-docker-dev-lambdarunner
        count: 1
        memory: 256
        cpu: 10

  - name: archive
    handler: archive.handler
    timeout: 300
    dlq: DispatcherFailedQueue # name of the dead letter queue
    # if broadcast is set to true, the lambda ARN is
    # included as an env variable
    broadcast: true

  - name: dispatcher
    handler: dispatcher.handler
    timeout: 300
    dlq: DispatcherFailedQueue
    broadcast: true

  - name: cmr
    handler: cmr.handler
    timeout: 300
    dlq: DispatcherFailedQueue
    broadcast: true

  - name: distribution
    handler: distribution.handler
    timeout: 300
    apiGateway:
      - api: distribution
        path: 'redirect'
        method: get
      - api: distribution
        path: '{granuleId}'
        method: get

  - name: stats
    handler: stats.handler
    timeout: 300
    apiGateway:
      - path: stats/summary
        method: get
        cors: true
        api: backend
      - path: stats/summary/grouped
        method: get
        cors: true
        api: backend

  - name: logs
    handler: logs.handler
    timeout: 300
    apiGateway:
      - path: stats/logs
        method: get
        cors: true
        api: backend
      - path: logs
        method: get
        cors: true
        api: backend

  - name: granules
    handler: granules.handler
    timeout: 300
    apiGateway:
      - path: granules
        method: get
        cors: true
        api: backend
      - path: granules/{granuleName}
        method: get
        cors: true
        api: backend
      - path: granules/{granuleName}
        method: put
        cors: true
        api: backend

  - name: collections
    handler: collections.handler
    timeout: 300
    apiGateway:
      - path: collections
        method: get
        cors: true
        api: backend
      - path: collections/{short_name}
        method: get
        cors: true
        api: backend
      - path: collections
        method: post
        cors: true
        api: backend
      - path: collections/{short_name}
        method: put
        cors: true
        api: backend

  - name: providers
    handler: providers.handler
    timeout: 300
    apiGateway:
      - path: providers
        method: get
        cors: true
        api: backend
      - path: providers/{name}
        method: get
        cors: true
        api: backend
      - path: providers
        method: post
        cors: true
        api: backend
      - path: providers/{name}
        method: put
        cors: true
        api: backend

  - name: pdrs
    handler: pdrs.handler
    timeout: 300
    apiGateway:
      - path: pdrs
        method: get
        cors: true
        api: backend
      - path: pdrs/{pdrName}
        method: get
        cors: true
        api: backend

  - name: schemas
    handler: schemas.handler
    timeout: 300
    apiGateway:
      - path: schemas/{schemaName}
        method: get
        cors: true
        api: backend
